### ISSUE TITLE
Priors of the nuisance parameters in Planck 2018 likelihood

### ISSUE THREAD

**Issue by adriagova** [baudren/montepython_public#133]
Hi,

I am trying to implement the Planck 2018 likelihood in MontePython. After reading the explanatory plc_3.0/readme_baseline.md file and taking also a look to the document hi_l/plik/plik_recommended_priors.txt it seems that some important information is missing in the latter. What are the central values and uncertainties for the priors of the following nuisance parameters: A_cib_217, xi_sz_cib, A_sz, A_planck, ksz_norm, ps_A_100_100, ps_A_143_143, ps_A_143_217, ps_A_217_217? Does anyone know? Do they coincide with the ones in Planck 2015 data release?

Thanks a lot!

**Comment by brinckmann** [comment]
Hi,

This github page is no longer being maintained. I have just released MontePython v3.2, which contains the Planck 2018 likelihoods with example param files. You can find these on the new MontePython github page:
[https://github.com/brinckmann/montepython_public](https://github.com/brinckmann/montepython_public)

Best,
Thejs

**Comment by adriagova** [comment]
Hi Thejs, 

thanks a lot for your help!

Best
