### ISSUE TITLE
error in running likelihoods after sourcing path to the PLC folder

### ISSUE THREAD

**Issue by trupti1729** [baudren/montepython_public#145]
During the installation of MontePython I get the following error in the final step after sourcing path to the PLC.
I searched online but available solutions couldn't solve this issue. Planck 2015 data and other things are installed as per the installation guide.
Can someone please help me with this issue ASAP.??
It will be a great help. Thank you in advance.

trupti@trupti-System-Product-Name:~/CLASS/montepython_public$ python montepython/MontePython.py -o planck/ -p base.param -c covmat/base.covmat -b bestfit/base.bestfit --conf default.conf -f 1.5
 /!\ Defaulting to the 'run' command. Please update the call of MontePython. For
     more info, see the help string and/or the documentation
Running Monte Python v2.2.2

with CLASS v3.0.0

Testing likelihoods for:
 -> Planck_highl, Planck_lowl, lowlike

Cannot use clik wrapper (cause = 'No module named lkl')
Cannot use clik_lensing wrapper (cause = 'No module named lkl_lensing')
 /!\ PyFITS is deprecated, please use astropy.io.fits
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/trupti/CLASS/montepython_public/montepython/run.py", line 31, in run
    custom_command)
  File "/home/trupti/CLASS/montepython_public/montepython/run.py", line 188, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/trupti/CLASS/montepython_public/montepython/initialise.py", line 66, in initialise
    data = Data(command_line, path)
  File "/home/trupti/CLASS/montepython_public/montepython/data.py", line 340, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/home/trupti/CLASS/montepython_public/montepython/data.py", line 460, in initialise_likelihoods
    elem, elem, folder, elem)
  File "<string>", line 1, in <module>
  File "/home/trupti/CLASS/montepython_public/montepython/likelihood_class.py", line 883, in __init__
    except clik.lkl.CError:
AttributeError: 'module' object has no attribute 'lkl'

**Comment by trupti1729** [comment]
After commenting out this line  "path['clik']            = root+'/plc_3.0/plc-3.01' " from default.conf file I ran the following command and get error different from the above one.

trupti@trupti-System-Product-Name:~/CLASS/montepython_public$ python montepython/MontePython.py -o planck/ -p base.param -c covmat/base.covmat \
> -b bestfit/base.bestfit --conf default.conf -f 1.5
 /!\ Defaulting to the 'run' command. Please update the call of MontePython. For
     more info, see the help string and/or the documentation
 /!\ Appending to an existing folder: using the log.param instead of base.param
Running Monte Python v2.2.2

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/trupti/CLASS/montepython_public/montepython/run.py", line 31, in run
    custom_command)
  File "/home/trupti/CLASS/montepython_public/montepython/run.py", line 208, in safe_initialisation
    " Alternatively, there could be a problem with "+e.message)
io_mp.ConfigurationError: 

Configuration Error:
 /|\   You are running in a folder that was created following a non-successful
/_o_\  initialisation (wrong parameter name, wrong likelihood, etc...). If you
       have solved the issue, you should remove completely the output folder,
       and try again. Alternatively, there could be a problem with cosmo

Kindly look into this issue and assist me soon.
Thank you.

**Comment by lesgourg** [comment]
Your are raising issues on the old MontePython repository (active in 2013-2018). As clearly stated on the wiki of this repository, since April 2018 and version 3.0, the MontePython repository  has moved to https://github.com/brinckmann/montepython_public
Please go there to clone recent, working and maintained versions of the code, and raise issues if necessary.
