### ISSUE TITLE
Adding derived parameters to a run without running the full simulation

### ISSUE THREAD

**Issue by baudren** [baudren/montepython_public#4]
One should be able to add nuisance parameters to an existing run, rewriting the chains with these added parameters. It would be pointless to do another Markov Chain process, as the analysis will not change.

It should then be possible to rewrite the chains automatically with the added derived parameters.

**Comment by arsalanadil** [comment]
Hi Benjamin,

I came across this ancient post just now. Do you recall how one can add derived parameters to a chain after it has finished running? I can't find anything of the sort in the docs. 

Best wishes,
Arsalan

**Comment by brinckmann** [comment]
You use the flags `--Der-target-folder` and `--Der-param-list`. See more information in the help files with:
`python montepython/MontePython.py run --help`

Best,
Thejs

**Comment by arsalanadil** [comment]
Got it. Thanks, Thejs!
