### ISSUE TITLE
Running Monte Python with MPI

### ISSUE THREAD

**Issue by borisbolliet** [baudren/montepython_public#46]
Hello!

First, merci beaucoup for all the useful information provided in the website. 

I am trying to run MP with mpirun following the indications given in "Example of a complete work session". 

I am working with the cluster CC-in2p3.

Here is the command:

$mpirun -np 4 python montepython/MontePython.py run -o chains --conf default.conf -p  base2015.param -c covmat/base.covmat -N 5

#Here is the output in the terminal:

run
Running Monte Python v2.1.4

with CLASS v2.4.2

Testing likelihoods for:
 -> Planck_highl

run
 /!\ Appending to an existing folder: using the log.param instead of
     base2015.param
Running Monte Python v2.1.4

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "montepython/run.py", line 31, in run
    custom_command)
  File "montepython/run.py", line 208, in safe_initialisation
    " Alternatively, there could be a problem with "+e.message)
io_mp.ConfigurationError: 

Configuration Error:
 /|\   You are running in a folder that was created following a non-successful
/_o_\  initialisation (wrong parameter name, wrong likelihood, etc...). If you
       have solved the issue, you should remove completely the output folder,
       and try again. Alternatively, there could be a problem with cosmo

.
[same 4 times, as I did np -4]
.

#Then the code runs, but only creates one chain:

clik version 6dc2a8cf3965
  smica
Checking likelihood '/sps/lsst/data/bbolliet/PlanckMCMC/plc-2.0/../plc_2.0/hi_l/plik/plik_dx11dr2_HM_v18_TT.clik' on test data. got -380.979 expected -380.979 (diff -8.68545e-09)

Creating chains/2015-08-25_5__1.txt
.
[blabbla]
.

Deduced starting covariance matrix:
['n_s', 'A_planck']
[[  5.30e-05   0.00e+00]
 [  0.00e+00   6.25e-02]]

  -LogLkl	n_s             1e+02A_planck   
5  2037.4	9.508254e-01	1.003987e+02	

5 steps done, acceptance rate: 0.2
/sps/lsst/data/bbolliet/PlanckMCMC(1)>ls chains/
2015-08-25_5__1.txt  log.param

#The doc about mpi_run in montepython says:

def mpi_run(custom_command=""):
    """
    Launch a simple MPI run, with no communication of covariance matrix

    Each process will make sure to initialise the folder if needed. Then and
    only then, it will send the signal to its next in line to proceed. This
    allows for initialisation over an arbitrary cluster geometry (you can have
    a single node with many cores, and all the chains living there, or many
    nodes with few cores). The speed loss due to the time spend checking if the
    folder is created should be negligible when running decently sized chains.

    Each process will send the number that it found to be the first available
    to its friends, so that the gathering of information post-run is made
    easier. If a chain number is specified, this will be used as the first
    number, and then incremented afterwards with the rank of the process.
    """

Either I am misusing the module, or It seems it is not doing the job...

Is there a way to fix this problem simply?

Many thanks
Boris

**Comment by borisbolliet** [comment]
The problem is that the module mpi4py is not installed in the default setting at the cluster CC-in2p3. 

To check if it installed on your system do:
$python
Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpi4py import MPI
>>> exit()

If you get an error message you shall install it:

LINUX

$apt-get install python-mpi4py

Mac OS

$pip install mpi4py


If there is no error message it is ok.

**Comment by baudren** [comment]
ok, good to know! Thank you for the question and fix!
