### ISSUE TITLE
Parameter arrays as MCMC parameters

### ISSUE THREAD

**Issue by DanBThomas** [baudren/montepython_public#54]
Hey

I just wondered what the best way is to handle parameters that are arrays in CLASS, when I want to use them as MCMC parameters?

For example, the array of m_ncdm masses. If I wanted two or three separate masses as independent MCMC parameters, how would I write this in the parameter file?

Thanks
Dan

**Comment by ThomasTram** [comment]
Hi,

there is a feature for that build into MontePython. If there is a CLASS input array, MontePython will understand __N as entries in this array. For instance, for the array ````scf_parameters```` MontePython automatically understand the input arguments
````
data.parameters['scf_parameters__1'] = [1.0,    0.0,  2.1,  0.5, 1, 'cosmo']
data.parameters['scf_parameters__2'] = [0.0,    None, None, 0.0, 1, 'cosmo']
data.parameters['scf_parameters__3'] = [0.0,    None, None, 0.0, 1, 'cosmo']
data.parameters['scf_parameters__4'] = [0.0,    None, None, 0.0, 1, 'cosmo']
data.parameters['scf_parameters__5'] = [0.0,    0.0,  5.0,  1.0, 1, 'cosmo']
data.parameters['scf_parameters__6'] = [1e-4,   None, None, 0.0, 1, 'cosmo']
data.parameters['scf_parameters__7'] = [0.0,    None, None, 0.0, 1, 'cosmo']
````

Note that all entries in the array needs to be specified as cosmological parameters. The non-varying should be None, None, 0.0 as shown above. Also note that counting starts with 1.

Cheers,
Thomas

**Comment by DanBThomas** [comment]
Excellent, thanks.
For the case of neutrino masses, m_ncdm, I have specified two of these as you suggested.
Also in the parameter file I have
data.cosmo_arguments['N_ncdm'] = 2
and I have added (I know these are the default values at the moment, but in case they need to be changed) 
data.cosmo_arguments['T_ncdm__1'] = 0.71611
data.cosmo_arguments['T_ncdm__2'] = 0.71611
However, when I do so, the output at the terminal includes
"Error in Class: Class did not read input parameter(s): T_ncdm__2, T_ncdm__1"

Have I got the syntax wrong for this?

Cheers
Dan

**Comment by ThomasTram** [comment]
>Note that all entries in the array needs to be specified as cosmological parameters.
The trick only works for ````data.parameters````, not ````cosmo_arguments````. That is why you need to specify them as non-varying as I showed.

Cheers,
Thomas

**Comment by DanBThomas** [comment]
Massive thanks for this!
Dan

**Comment by ThomasTram** [comment]
Glad I could help!
