### ISSUE TITLE
Problem with scf_parameters 

### ISSUE THREAD

**Issue by Chibana** [baudren/montepython_public#60]
Hello, 

I'm trying to use Monte Python with quintessence but I'm having troubles passing the scalar field parameters. I'm trying something like this

`data.cosmo_arguments['scf_parameters'] = 10.0, 0.0, 0.0, 0.0, 100.0, 0.01`

and returns the error

> Cosmological Module Error:
>   /|\   Something went wrong when calling CLASS
> /_o_\  Error in Class: input_init(L:402) :error in
>        input_read_parameters(&(fzw.fc), ppr, pba, pth, ppt, ptr, ppm, psp, pnl,
>        ple, pop, errmsg);
>        =>input_read_parameters(L:1004) :error in
>        parser_read_list_of_doubles(pfc, "scf_parameters",
>        &(pba->scf_parameters_size), &(pba->scf_parameters), &flag1, errmsg);
>        =>parser_read_list_of_doubles(L:432) :condition
>        (sscanf(string_with_one_value,"%lg",&(list[i-1])) != 1) is true; could
>        not read 1th value of list of parameters scf_parameters in file NOFILE

So, how should I do it?

Thanks!

**Comment by ThomasTram** [comment]
Hi,

if you want to just fix all your scf_parameters to these values, you need to make the list of numbers a string. However, given that you probably need to vary one or more of the parameters, have a look here: https://github.com/baudren/montepython_public/issues/54

Cheers,
Thomas Tram

**Comment by Chibana** [comment]
Hi Thomas, 

Thank you for the quick reply. Indeed I'll need to vary some of the parameters.

Cheers, 
Fabio

**Comment by ajcosmology** [comment]
Hello,
Did you manage to resolve the issue? I am trying Montepython with scalar field parameters but having problems with the input .param file. If you managed to resolve it, can you please help me and explain how you defined the scalar field parameters in the .param file. 
Thanks,
Alex
