### ISSUE TITLE
Missing montepython/likelihoods/__init__.py file

### ISSUE THREAD

**Issue by ardok-m** [baudren/montepython_public#67]
Hi,
The `__init__.py` file is missing in `montepython/likelihoods` folder:

> Configuration Error:
>  /|\   Trying to import the fake_planck_bluebook likelihood as asked in the
> /_o_\  parameter file, and failed. Please make sure it is in the
>        `montepython/likelihoods` folder, and is a proper python module. Check
>        also that the name of the class defined in the `__init__.py `matches the
>        name of the folder. In case this is not enough, here is the original
>        message: No module named likelihoods.fake_planck_bluebook

I've solved (or at least it does not complain any longer) this issue with:
`touch montepython/likelihoods/__init__.py`

**Comment by lesgourg** [comment]
Thank you, it is fixed now in 2.2 ! Sorry for the delay in fixing this.
