### ISSUE TITLE
getting a nan value for sigma of cosmological parameters in using montepython

### ISSUE THREAD

**Issue by mahtaparsa** [baudren/montepython_public#78]
Dear all,
When I use montepython for constraining the cosmological parameters, a nan value for sigma, 1-sigma, 2-sigma, ... would appear, and in likelihood diagrams there is "+nan" value for sigma related to cosmo, nuisance (usually for Planck data), or derived parameters. I can not understand what is the problem. Thanks your suggestions.

**Comment by ivandebono** [comment]
The problem it your chains have not converged. Either because you haven't sampled enough points (you set the number using the -N setting), or for a variety of reasons, such as poor constraints from the data or parameter degeneracy.
