### ISSUE TITLE
fitting the parameters with data

### ISSUE THREAD

**Issue by mahtaparsa** [baudren/montepython_public#87]
Hi everybody,
In using montepython, how the data fit to the model? For example when in "log.param" file we have 'output': 'mPk tCl lCl pCl ' what does it mean? Are the best fit values of the six parameters of the LCDM model constrain with the temperature anisotropy spectrum, the polarization anisotropy spectrum and the CMB lensing potential , while the best fit value of the sigma_8 is constrained with the matter power spectrum? Or the mPk play a role in constraining all parameters? In better words, the parameters of the model fit to which spectrum in order to find the best fit? the matter power spectrum or the CMB anisotropy spectrum?
Thanks

**Comment by borisbolliet** [comment]
Dear mahtaparsa,

You mean: "how the model fits the data?"

Anyway, this all depends on what data you are talking about, specified in data.experiment[...] in your param file. For instance, for a CMB experiment there is no data relative to the matter power spectrum itself, mPk, the likelihood is computed based on the CMB Cl's data. This yields posterior probability contours for the six parameters of LCDM, in particular As and Omega_m and therefore sigma8 too. 

Finally, to answer the second part of your question, generally, you can not say: 'this' data constrains 'this' parameter and 'that' data constrains 'that' parameter. There is often a degeneracy between different parameters. The goal of an MCMC analysis is to explore those degeneracies.

I hope this helps,
Boris
