### ISSUE TITLE
A likelihood for Redshift Space Distortions (RSD)  ?

### ISSUE THREAD

**Issue by borisbolliet** [baudren/montepython_public#93]
Hi all,

As far as I understand, in the current version of MontePython (MP) there is no likelihood or data for RSD.

It seems to me that the likelihoods associated with galaxy surveys in the current MP version (SDSS, WiggleZ, etc) are only referring to the BAO scale, but not to the growth rate f*sigma8. 

Please correct me if I am wrong.

Thank you very much,
Boris

**Comment by brinckmann** [comment]
Hi Boris,
Yes, currently there is no RSD likelihood for WiggleZ and SDSS, only P(k) and BAO likelihoods. A BAO+RSD likelihood should be in the upcoming MontePython release.
Best,
Thejs

**Comment by lesgourg** [comment]
Boris, internally Thejs has already implemented the BAO+RSD likelihood for SDSS DR12. As he said, we will include it in the next release, but do you want that we send it to you before, just as a patch?

**Comment by chenggongphy** [comment]
Hi Lesgourg,
I want to use the RSD likelihood to constrain the parameters of my model. So can you kindly send me the likelihood in advance?
Thank you.
Best,
Cheng Gong

**Comment by borisbolliet** [comment]
Dear Julien and Thejs,

Thank you very much for your response. Personally, I can wait for the next release. 

I close this issue cause you have answered my question (but discussion remains open, of course :-)). 

Best,
Boris
